function [PHY3D] = jamstecrest_gaussecomodel1D_convertodiscrete(PHYT,logESD,logESDave,logESDstd)

%========================================================================
%........................................................................
[mdepths,mdays] = size(logESDave); 
%........................................................................
for zdepthj = 1:mdepths 
    zdepthj 
    for dayj = 1:mdays 
	%................................................................
	deltax = diff(logESD); 
	deltax = [deltax(1),deltax]; %to recover original length.
	%................................................................
	phytot = PHYT(zdepthj,dayj);
	%................................................................
	logESDavej = logESDave(zdepthj,dayj);
	logESDstdj = logESDstd(zdepthj,dayj);
	%................................................................
	PDF = (1.0 / (logESDstdj * sqrt(2*pi))) * exp( -(logESD - logESDavej).^2 / (2*logESDstdj^2) );
	%................................................................
	sumPDF = sum(PDF .* deltax); %should be equal to one!!! (for an infinite range of logESD)
	%................................................................
	PHY3D(zdepthj,dayj,:) = phytot * (PDF .* deltax); %Phy size distribution at t0. 
	%................................................................
    end
end
%........................................................................
%========================================================================

