function [ChlaToCarbonRatio,CarbonToChlaRatio]=myChlaToCarbonRatio(PARwatt,PARunits)

%***************************************************
%Use: ChlaToCarbonRatio,CarbonToChlaRatio]=myChlaToCarbonRatio(PARwatt)
%
%***************************************************

%.......................................................
[ndepths,ndays] = size(PARwatt);
%.......................................................
time = [1:ndays];
%.......................................................
fcPAR = 2.5; %factor de conversion de [Einstein*m-2*d-1] a [W*m-2] para 400-700nm (PAR)
%.......................................................
%=======================================================
%.......................................................
if strcmp(PARunits,'Einsteins')
    [PAReins] = PARwatt; %[Einstein*m-2*d-1]
elseif  strcmp(PARunits,'Watts')
    [PAReins]=myPARconversion(PARwatt,'Watts-to-Einstains'); %[Einstein*m-2*d-1]
end
%.......................................................
%=======================================================
%.......................................................
PAR2D = PAReins; %Detph resolved PAR [Einstein*m-2*d-1]
%.......................................................
parz0 = PAR2D(1,:); %Surface PAR.
%.......................................................
parz0min = min(parz0(:));
parz0max = max(parz0(:));
%.......................................................
minPAR2D = min(PAR2D(:));
maxPAR2D = max(PAR2D(:));
%.......................................................
PARz0 = (parz0(:)*ones(1,ndepths))'; %[200m,365days]
%.......................................................
%=======================================================
%.......................................................
PAR2DnormA = PAR2D/parz0max; %Pcnt of max surface PAR [0 - 1]
%.......................................................
PAR2DnormB = sqrt(PAR2D/parz0max); %Pcnt of max surface PAR [0 - 1]
%.......................................................
PAR2DnormC = (PAR2D/parz0max).^(1/3); %Pcnt of max surface PAR [0 - 1]
%.......................................................
PAR2DnormD = (PAR2D/parz0max).^(1/15); %Pcnt of max surface PAR [0 - 1]
%.......................................................
PAR2Dnorm = PAR2DnormD;
%.......................................................
%=======================================================
%.......................................................
PAR2Dpcnt = PAR2D./PARz0; %Pcnt of surface PAR [0 - 1]
%.......................................................
%=======================================================
PAR2DnormLogA = log(PAR2D)./log(parz0max);
PAR2DnormLogB = (log(PAR2D)-log(parz0max))./log(parz0max);
PAR2DnormLogC = (log(PAR2D)-log(parz0max))./(log(parz0min)-log(parz0max));
%.......................................................
PAR2DnormLog = (1 - PAR2DnormLogC / max(PAR2DnormLogC(:)));
%.......................................................
%=======================================================
%.......................................................
% $$$ maxCarbonToChlaRatio = 250.00;  %[mgC*mgCHL-1] (see GOERICKE and WELSCHMEYER 1998, JPR 20, Fig.8d)
% $$$ minCarbonToChlaRatio =  50.00;
%.......................................................
maxCarbonToChlaRatio = 200.00;  %[mgC*mgCHL-1] (see GOERICKE and WELSCHMEYER 1998, JPR 20, Fig.8d)
minCarbonToChlaRatio =  50.00;
%.......................................................
maxPAR = 50.00; %[Einstein*m-2*d-1]
minPAR = 10.00;
%.......................................................
%=======================================================
%.......................................................
pcntThres = 0.40; %Threshold at 40% of maximum surface PAR (see GOERICKE and WELSCHMEYER 1998, JPR, Fig.7c-summer)
%.......................................................
PPAR2Dpcnt = PAR2Dpcnt;
J = find(PAR2Dpcnt > pcntThres);
PPAR2Dpcnt(J) = pcntThres;
%.......................................................
%=======================================================
%.......................................................
xsurface = parz0; %PAR
%.......................................................
% $$$ xsurface = [0:0.1:60]; %PAR (ONLY FOR PLOTING!!)
%.......................................................
%=======================================================
%.......................................................
ysurface1 = myfunsun(maxCarbonToChlaRatio,minCarbonToChlaRatio,xsurface,parz0max,parz0min);
%.......................................................
%=======================================================
%.......................................................
% $$$ CarbonToChlaRatio100m = 0.00; %Carbon-To-Chla ratio when PAR is very low (see GOERICKE and WELSCHMEYER 1998, JPR, Fig.6d)
%.......................................................
CarbonToChlaRatio100m = 20.00; %Carbon-To-Chla ratio when PAR is very low (see GOERICKE and WELSCHMEYER 1998, JPR, Fig.6d)
%.......................................................
% $$$ CarbonToChlaRatio100m = 25.00; %Carbon-To-Chla ratio when PAR is very low (see GOERICKE and WELSCHMEYER 1998, JPR, Fig.6d)
%.......................................................
% $$$ CarbonToChlaRatio100m = 50.00; %Carbon-To-Chla ratio when PAR is very low  %(see WANG etal. [2009] Biogeosciences, 6. Fig.1))
%.......................................................
alfa = CarbonToChlaRatio100m; %Intercept (ie. Carbon-To-Chla ratio when PAR is zero)
%.......................................................
% $$$ alfa = CarbonToChlaRatio100m/2; %Intercept (ie. Carbon-To-Chla ratio when PAR is zero)
%.......................................................
% $$$ alfa = 0; %Intercept (ie. Carbon-To-Chla ratio when PAR is zero)
%.......................................................
beta = (maxCarbonToChlaRatio - minCarbonToChlaRatio) / (maxPAR - minPAR);
%.......................................................
ysurface2 = alfa + beta*xsurface;
%.......................................................
%=======================================================
%.......................................................
ksat = mean([minPAR,maxPAR]); %anual mean of surface PAR;
%.......................................................
% $$$ ysurface3 = alfa + maxCarbonToChlaRatio * (xsurface ./ (ksat + xsurface));
%.......................................................
ysurface3 = alfa + maxCarbonToChlaRatio * (1 - exp(-(1/ksat)*xsurface));
%.......................................................
%=======================================================
%.......................................................
betaLog = (log(maxCarbonToChlaRatio) - log(minCarbonToChlaRatio)) / (log(maxPAR) - log(minPAR));
%.......................................................
ysurface4 = alfa + betaLog*xsurface;
%.......................................................
%=======================================================
%.......................................................
% $$$ figure(1)
% $$$ subplot(2,2,1)
% $$$ plot(xsurface,ysurface1,'b*')
% $$$ axis([0 60, 0 300])
% $$$ grid on
% $$$ subplot(2,2,2)
% $$$ plot(xsurface,ysurface2,'b*')
% $$$ axis([0 60, 0 300])
% $$$ grid on
% $$$ subplot(2,2,3)
% $$$ plot(xsurface,ysurface3,'b*')
% $$$ axis([0 60, 0 300])
% $$$ grid on
% $$$ subplot(2,2,4)
% $$$ plot(xsurface,ysurface4,'b*')
% $$$ axis([0 60, 0 300])
% $$$ grid on
% $$$ pause
%.......................................................
% $$$ figure(2)
% $$$ subplot(2,2,1)
% $$$ plot(time,xsurface,'r*-')
% $$$ subplot(2,2,2)
% $$$ plot(time,ysurface1,'r*-')
% $$$ subplot(2,2,3)
% $$$ plot(time,ysurface2,'r*-')
% $$$ subplot(2,2,4)
% $$$ plot(ysurface1,ysurface2,'b*')
% $$$ axis([0 300, 0 300])
% $$$ grid on
% $$$ %.......................................................
% $$$ pause
%=======================================================
%.......................................................
% $$$ CarbonToChlaRatioz0 = ysurface1;
%.......................................................
CarbonToChlaRatioz0 = ysurface2; %USAR ESTE!!!!
%.......................................................
% $$$ CarbonToChlaRatioz0 = ysurface3;
%.......................................................
%=======================================================
%.......................................................
% $$$ Beta = ( CarbonToChlaRatioz0(:) - minCarbonToChlaRatio); %(365,1)) [mgC*mgCHL-1]
%.......................................................
Beta = ( CarbonToChlaRatioz0(:) - alfa); %(365,1) [mgC*mgCHL-1]
%.......................................................
BETA = (Beta*ones(1,ndepths))'; %(200m,365days)
%.......................................................
Xstar = PPAR2Dpcnt/pcntThres; %Normalized PARpcnt [0 - 1] adim.
%.......................................................
% $$$ Xstar = PPAR2Dpcnt/pcntThres; %Normalized PARpcnt [0 - 1]
%.......................................................
% $$$ CarbonToChlaRatio = minCarbonToChlaRatio + (BETA .* Xstar); %[mgC*mgCHL-1]
%.......................................................
CarbonToChlaRatio1 = alfa + (BETA .* Xstar); %[mgC*mgCHL-1]
%.......................................................
ChlaToCarbonRatio1 = 1./CarbonToChlaRatio1;  %[mgCHL*mgC-1]
%.......................................................
%=======================================================
%.......................................................
CarbonToChlaRatio2 = alfa + beta*PAR2D; %[mgC*mgCHL-1]
%.......................................................
ChlaToCarbonRatio2 = 1./CarbonToChlaRatio2;  %[mgCHL*mgC-1]
%.......................................................
%=======================================================
%.......................................................
% $$$ CarbonToChlaRatio3 = alfa + maxCarbonToChlaRatio * (PAR2D ./ (ksat + PAR2D)); %[mgC*mgCHL-1]
%.......................................................
CarbonToChlaRatio3 = alfa + maxCarbonToChlaRatio * (1 - exp(-(1/ksat)*PAR2D)); %[mgC*mgCHL-1]
%.......................................................
ChlaToCarbonRatio3 = 1./CarbonToChlaRatio3;  %[mgCHL*mgC-1]
%.......................................................
%=======================================================
%.......................................................
pcntThres = 0.01;
%.......................................................
Beta = CarbonToChlaRatioz0; %[mgC*mgCHL-1]
%.......................................................
BETA = (Beta(:)*ones(1,ndepths))'; %(200m,365days)
%.......................................................
GAMA = (log(PARz0)-log(PAR2D))/(log(1.00)-log(pcntThres)); %(see WANG etal. [2009] Biogeosciences, 6. eq(5))
%.......................................................
H = find(GAMA > 1); %Deep dephths with PAR levels lower than "0.01*parz0".
%.......................................................
GAMA(H) = 1;
%.......................................................
% $$$ figure(1)
% $$$ GAMA = (1 - PAR2DnormLog);
% $$$ imagesc(GAMA),colorbar,pause
% $$$ % $$$ GAMA = GAMA .* (1 - PAR2Dnorm);
% $$$ GAMA = GAMA .* (1 - PAR2DnormLog);
% $$$ figure(2)
% $$$ imagesc(GAMA),colorbar,pause
%.......................................................
Alfa = alfa + (pcntThres*Beta); %[365days]
ALFA = (Alfa(:)*ones(1,ndepths))'; %(200m,365days)
ALFA = ALFA .* PAR2Dnorm;
%.......................................................
% $$$ Alfa = pcntThres*Beta; %[365days]
% $$$ ALFA = (Alfa(:)*ones(1,ndepths))'; %(200m,365days)
% $$$ ALFA = alfa + (ALFA .* PAR2Dnorm);
%.......................................................
% $$$ figure(2)
% $$$ imagesc(ALFA),colorbar
% $$$ pause
%.......................................................
CarbonToChlaRatio4 = BETA - (BETA - alfa) .* GAMA; %(see WANG etal. [2009] Biogeosciences, 6. eq(5))
%.......................................................
% $$$ CarbonToChlaRatio4 = BETA - (BETA - ALFA) .* GAMA;
%.......................................................
ChlaToCarbonRatio4 = 1./CarbonToChlaRatio4;  %[mgCHL*mgC-1]
%.......................................................
%=======================================================

%%%%%%%%%
%OUTPUTS:
%%%%%%%%%
%.......................................................
% $$$ CarbonToChlaRatio =    CarbonToChlaRatio1; %[mgC*mgCHL-1]
% $$$ ChlaToCarbonRatio = 1./CarbonToChlaRatio1; %[mgCHL*mgC-1]
%.......................................................
CarbonToChlaRatio =    CarbonToChlaRatio2; %[mgC*mgCHL-1] %USAR ESTE!!!!
ChlaToCarbonRatio = 1./CarbonToChlaRatio2; %[mgCHL*mgC-1]
%.......................................................
% $$$ CarbonToChlaRatio =    CarbonToChlaRatio3; %[mgC*mgCHL-1]
% $$$ ChlaToCarbonRatio = 1./CarbonToChlaRatio3; %[mgCHL*mgC-1]
%.......................................................

%%%%%%%
%PLOTS:
%%%%%%%
%=======================================================
% $$$ figure(3)
% $$$ subplot(2,2,1)
% $$$ imagesc(CarbonToChlaRatio1,[0 250])
% $$$ colorbar
% $$$ grid on
% $$$ subplot(2,2,2)
% $$$ imagesc(CarbonToChlaRatio2,[0 250])
% $$$ colorbar
% $$$ grid on
% $$$ subplot(2,2,3)
% $$$ imagesc(CarbonToChlaRatio3,[0 250])
% $$$ colorbar
% $$$ grid on
% $$$ subplot(2,2,4)
% $$$ imagesc(CarbonToChlaRatio4,[0 250])
% $$$ colorbar
% $$$ grid on
% $$$ %.......................................................
% $$$ figure(4)
% $$$ subplot(2,2,1)
% $$$ imagesc(ChlaToCarbonRatio1,[0.00 0.05])
% $$$ colorbar
% $$$ grid on
% $$$ subplot(2,2,2)
% $$$ imagesc(ChlaToCarbonRatio2,[0.00 0.05])
% $$$ colorbar
% $$$ grid on
% $$$ subplot(2,2,3)
% $$$ imagesc(ChlaToCarbonRatio3,[0.00 0.05])
% $$$ colorbar
% $$$ grid on
% $$$ subplot(2,2,4)
% $$$ imagesc(ChlaToCarbonRatio4,[0.00 0.05])
% $$$ colorbar
% $$$ grid on
% $$$ %.......................................................
%=======================================================
% $$$ %.......................................................
% $$$ % $$$ X = ones(ndepths,ndays)*nan;
% $$$ % $$$ Y = ones(ndepths,ndays)*nan;
% $$$ % $$$ %.......................................................
% $$$ % $$$ X(J) = PAR2D(J);
% $$$ % $$$ Y(J) = CarbonToChlaRatio(J);
% $$$ %.......................................................
% $$$ X = PAR2D(1:2,:);
% $$$ Y = CarbonToChlaRatio(1:2,:);
% $$$ %.......................................................
% $$$ x = nanmean(X,1);
% $$$ y = nanmean(Y,1);
% $$$ %.......................................................
% $$$ figure(5)
% $$$ subplot(2,2,1)
% $$$ plot(x,y,'*')
% $$$ axis([0 60, 0 300])
% $$$ grid on
% $$$ pause
% $$$ subplot(2,2,2)
% $$$ plot(time,x,'r-',time,y,'b-')
% $$$ grid on
% $$$ %.......................................................
%=======================================================
