function [mXout]=myMonthlyAve(X,AveType)

X = squeeze(X);
%..........................
[msize,nsize,psize]=size(X)
%..........................
if strcmp(AveType,'Weekly')
    nbins=60;
elseif strcmp(AveType,'Monthly')
    nbins=12;
elseif strcmp(AveType,'Seasonal')
    nbins=4;
end
%..........................
Xdims = ndims(X)
pause 
%..........................
if Xdims==3 %Array3D
    tmax = psize;
    mX=ones(msize,nsize,nbins);
else %Array2D or Vector1D
    tmax = nsize;
    mX=ones(msize,nbins);
end
%..........................
DeltaMonth = tmax*(1/nbins);
%..........................
c=0;
kk=1;
for k=1:DeltaMonth:tmax
    %..................
    c=c+1;
    %..................
    k1=kk;
    k2=kk+DeltaMonth-1;
    %..................
    J = [k1:k2];
    %..................
    if Xdims==3 %Array3D
	%..................
	Xk=X(:,:,J);
	%..................
	mXk=nanmean(Xk,3);
	%..................
	mX(:,:,c)=mXk;
	%..................
    else
	%..................
	Xk=X(:,J);
	%..................
	mXk=nanmean(Xk,2);
	%..................
	mX(:,c)=mXk;
	%..................
    end
    %..................
    kk=k2+1;
    %..................
end

%%%%%%%%
%OUTPUT:
%%%%%%%%
mXout = squeeze(mX);
