function [xssp]=myNewtonMethod(f,x)

tol = 10^(-5);
while 1 %infinite loop.
    %..........................................
    fx = feval(f,x);
    Jfx = myNumJacobianFast(f,x);
    %..........................................
% $$$     deltax = inv(Jfx)*fx; %[d] x [mmolN*m-3*d-1] = [mmolN*m-3]
    %..........................................
    deltax =     Jfx\ fx; %[d] x [mmolN*m-3*d-1] = [mmolN*m-3]
    %..........................................
    x2 = x - deltax; %Get the next point.
    %..........................................
    fx2 = feval(f,x2);
    %..........................................
    if norm(fx2) < tol %Check error tolerate.
	xssp = x2;
	return;
    end
    %..........................................
    x = x2;
    %..........................................
end  
%..............................................
